[package]
name = "orx-priority-queue"
version = "0.1.3"
edition = "2021"
authors = ["orxfun"]
description = "Priority queue traits and generalized d-ary heap implementations."
license = "MIT"
documentation = ""


[dependencies]

[dev-dependencies]
itertools = "0.11.0"
rand = "0.8.5"
